### ISSUE TITLE
Cached responses for json result in application/octet-stream

### ISSUE THREAD

**Issue by dudevon** [theodi/uk-postcodes#39]
For example `http://uk-postcodes.com/postcode/SG2 8TN.json` returns Headers with

```
Cache-Control →max-age=0, private, must-revalidate
Connection →keep-alive
Content-Type →application/json; charset=utf-8
Date →Thu, 30 Oct 2014 12:58:13 GMT
ETag →"6003e3e383be8b6cabda98ff09ef3d21"
Server →nginx/1.4.4 + Phusion Passenger 4.0.29
Status →200 OK
Transfer-Encoding →chunked
X-Powered-By →Phusion Passenger 4.0.29
X-Rack-Cache →miss
X-Request-Id →f51aeef4d3f47340d101f9bbffab8dae
X-Runtime →1.159144
X-UA-Compatible →IE=Edge,chrome=1
```

Subsequent requests for the same endpoint url the headers change to:

```
Accept-Ranges →bytes
Connection →keep-alive
Content-Length →814
Content-Type →application/octet-stream
Date →Thu, 30 Oct 2014 13:00:27 GMT
ETag →"545235e5-32e"
Last-Modified →Thu, 30 Oct 2014 12:58:13 GMT
Server →nginx/1.4.4
```

**Comment by romanwozniak** [comment]
Is there any chance to fix it? Or maybe someone knows any workaround? Thanks.

**Comment by kangarolf** [comment]
I believe I am running into this issue as well.

**Comment by pezholio** [comment]
Sorry, I missed @JeniT's response to this. I've had a horrible hack to work around this by clearing the cache out, but now I know the underlying issue, I'll try and get it fixed ASAP

**Comment by kangarolf** [comment]
Cheers..I guess you are working on it right now as its behaving funny.

**Comment by adnansorg** [comment]
looks solved to me
