### ISSUE TITLE
Server error (no postcode lookup)

### ISSUE THREAD

**Issue by girishkumarkh** [theodi/uk-postcodes#43]
I guess the ruby application has an server issue. which needs fixing.

http://www.uk-postcodes.com/postcode/search?utf8=✓&q=cf244bs&format=html&button=

**Comment by pezholio** [comment]
Yeah, the box got a little full, as the cache got a bit full. I've cleared it out, and everything seems to be back to normal now. Sorry!

**Comment by girishkumarkh** [comment]
:+1: Awesome! Thanks for sorting it out
