### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by rmillo8** [theodi/uk-postcodes#46]
Hi,
 the service seems to be down at the moment: see screenshot

E.g. http://www.uk-postcodes.com/postcode/N1c%204ab.xml is returning

![postcode error](https://cloud.githubusercontent.com/assets/8375318/10690864/ac1487e4-797c-11e5-9ae8-2ac816f9d844.PNG)

If you could have a look at this it would be really great.

Thanks!

Raf

**Comment by pezholio** [comment]
This is all fixed now. Apologies for the delay. I'm hoping to deploy some fixes soon to improve stability long term.
